// Shared DOM references, runtime state, and immutable configuration.
// Feature modules register their public functions on `app`.

export const app = {};

export const dom = {
  nameInput: document.getElementById("name-input"),
  createBtn: document.getElementById("create-btn"),
  resumeGamePanel: document.getElementById("resume-game-panel"),
  resumeGameDescription: document.getElementById("resume-game-description"),
  resumeGameBtn: document.getElementById("resume-game-btn"),
  commandInput: document.getElementById("command-input"),
  terminal: document.getElementById("terminal"),
  startScreen: document.getElementById("start-screen"),
  lobbyScreen: document.getElementById("lobby-screen"),
  gameScreen: document.getElementById("game-screen"),
  refreshLobbiesBtn: document.getElementById("refresh-lobbies-btn"),
  openLobbiesStatus: document.getElementById("open-lobbies-status"),
  openLobbiesList: document.getElementById("open-lobbies-list"),
  errorMsg: document.getElementById("error-msg"),
  lobbyGameId: document.getElementById("lobby-game-id"),
  lobbyPlayerCount: document.getElementById("lobby-player-count"),
  lobbyPlayers: document.getElementById("lobby-players"),
  lobbyChoiceForm: document.getElementById("lobby-choice-form"),
  rulePresetSelect: document.getElementById("rule-preset-select"),
  rulePresetSummary: document.getElementById("rule-preset-summary"),
  customRulesEditor: document.getElementById("custom-rules-editor"),
  customRulesFields: document.getElementById("custom-rules-fields"),
  resetCustomRules: document.getElementById("reset-custom-rules"),
  lobbyRulesPanel: document.getElementById("lobby-rules-panel"),
  lobbyRulesPreset: document.getElementById("lobby-rules-preset"),
  lobbyRulesList: document.getElementById("lobby-rules-list"),
  gameRulesPanel: document.getElementById("game-rules-panel"),
  gameRulesPreset: document.getElementById("game-rules-preset"),
  gameRulesList: document.getElementById("game-rules-list"),
  teamSelect: document.getElementById("team-select"),
  gameModeSelect: document.getElementById("game-mode-select"),
  colorSelects: document.getElementById("color-selects"),
  confirmLobbyChoice: document.getElementById("confirm-lobby-choice"),
  lobbyStatus: document.getElementById("lobby-status"),
  lobbyError: document.getElementById("lobby-error"),
  gameIdDisplay: document.getElementById("game-id-display"),
  dealerName: document.getElementById("dealer-name"),
  connectionStatus: document.getElementById("connection-status"),
  connectionStatusText: document.getElementById("connection-status-text"),
  currentPlayerName: document.getElementById("current-player-name"),
  turnInstruction: document.getElementById("turn-instruction"),
  turnBanner: document.querySelector(".turn-banner"),
  cancelCardSelection: document.getElementById("cancel-card-selection"),
  localHandSlot: document.getElementById("local-hand-slot"),
  emptyHandMessage: document.getElementById("empty-hand-message"),
  board: document.getElementById("board"),
  discardPile: document.getElementById("discard-pile"),
  discardPileCard: document.getElementById("discard-pile-card"),
  languageSelect: document.getElementById("language-select"),
  boardViewportElement: document.getElementById("board-viewport"),
  boardWrapperElement: document.getElementById("board-wrapper"),
};

export const i18n = window.tocI18n;

export const state = {
  selectableSpotHandlers: new Map(),
  ws: null,
  local_player_name: null,
  local_game_Id: null,
  local_player: null,
  local_card_box: null,
  local_info_box: null,
  currentLobbyState: null,
  ruleConfiguration: null,
  displayedRuleset: null,
  stored_player_name: window.localStorage.getItem("session_player_name"),
  stored_game_id: window.localStorage.getItem("session_game_ID"),
  activeRequestId: null,
  openLobbies: [],
  openLobbiesRequestInProgress: false,
  backendMessageElements: new Map(),
  activityMessages: [],
  totalRegions: 4,
  spotsPerRegion: 18,
  enterHouseAtSpot: 18,
  totalSpots: 72,
  starStepAngleCache: new Map(),
  spotElements: [],
  houseElements: [],
  playerAssignments: [],
  usedColors: [],
  usedPositions: [],
  selectedCard: null,
  pendingExchangeCards: new Map(),
  cardAnimationId: 0,
};

export const constants = Object.freeze({
  SERVER_UNREACHABLE_CODE: 1006,
  NO_GAME_FOUND_CODE: 4001,
  NO_PLAYER_CONTEXT_FOUND_CODE: 4002,
  GAME_ALREADY_FULL_CODE: 4004,
  CONNECTION_IDENTIFICATION_ERROR_CODE: 4005,
  LOBBY_EXPIRED_CLOSE_CODE: 4006,
  GAME_SUSPENDED_CLOSE_CODE: 4007,
  START_NOTICE_STORAGE_KEY: "toc.startNotice",
  RULE_GROUPS: Object.freeze({
    round: "rules.groups.round",
    board: "rules.groups.board",
    special: "rules.groups.special",
    seven: "rules.groups.seven",
  }),
  RULE_UI: Object.freeze({
    card_exchange: {group: "round"}, shuffle_cards: {group: "round"},
    rotation: {group: "round"}, deal_card_counts: {group: "round"},
    cannot_play_folds_entire_hand: {group: "round"},
    exit_spot_is_protected_and_blocking: {group: "board"},
    house_spots_are_blocking_and_protected: {group: "board"},
    landing_on_occupied_spot_kicks_piece: {group: "board"},
    track_region_length: {group: "board"}, enter_house_at_spot: {group: "board"},
    four_can_move_backward: {group: "special"}, can_enter_house_backward: {group: "special"},
    five_behaviour: {group: "special"}, jacks_can_switch: {group: "special"},
    jacks_can_switch_then_seven_hop: {group: "special"}, ace_values: {group: "special"},
    king_kicks_pieces_on_path: {group: "special"}, joker_kicks_pieces_on_path: {group: "special"},
    seven_can_split: {group: "seven"}, seven_split_kicks_pieces_on_path: {group: "seven"},
    seven_hopping: {group: "seven"}, five_hop_decider: {group: "seven"},
    seven_hopping_on_four_backward_goes_backward: {group: "seven"},
  }),
  radius: 250,
  centerX: 300,
  centerY: 300,
  boardLayoutWidth: 720,
  boardLayoutHeight: 700,
  boardTopSpacing: 8,
  houseLabels: Object.freeze(["T", "O", "C", "!"]),
  spotsPerHouse: 4,
  houseDistance: 40,
  starBoardConfigurations: Object.freeze({
    4: {innerRadius: 150, armLength: 100, sharpness: 2.05},
    6: {innerRadius: 185, armLength: 65, sharpness: 1.85},
  }),
  boardSurfaceMargin: 43,
  boardShapeSamples: 180,
  starCurveSamplesPerBranch: 360,
  seatLayouts: Object.freeze({
    2: [
      {position: "bottom-right", regionIndex: 0},
      {position: "top-left", regionIndex: 1},
    ],
    4: [
      {position: "top-left", regionIndex: 2},
      {position: "top-right", regionIndex: 3},
      {position: "bottom-right", regionIndex: 0},
      {position: "bottom-left", regionIndex: 1},
    ],
    6: [
      {position: "bottom-right", regionIndex: 0},
      {position: "bottom-center", regionIndex: 1},
      {position: "bottom-left", regionIndex: 2},
      {position: "top-left", regionIndex: 3},
      {position: "top-center", regionIndex: 4},
      {position: "top-right", regionIndex: 5},
    ],
  }),
  positionMap: Object.freeze({
    "top-left": {info_box: document.getElementById("player-info-top-left"), card_box: document.getElementById("card-box-top-left")},
    "top-center": {info_box: document.getElementById("player-info-top-center"), card_box: document.getElementById("card-box-top-center")},
    "top-right": {info_box: document.getElementById("player-info-top-right"), card_box: document.getElementById("card-box-top-right")},
    "bottom-left": {info_box: document.getElementById("player-info-bottom-left"), card_box: document.getElementById("card-box-bottom-left")},
    "bottom-center": {info_box: document.getElementById("player-info-bottom-center"), card_box: document.getElementById("card-box-bottom-center")},
    "bottom-right": {info_box: document.getElementById("player-info-bottom-right"), card_box: document.getElementById("card-box-bottom-right")},
  }),
  PLAYER_ACCENT_RGB: Object.freeze({
    red: "220, 38, 38", green: "22, 163, 74", blue: "37, 99, 235", yellow: "234, 179, 8",
    orange: "234, 88, 12", purple: "147, 51, 234", pink: "219, 39, 119", cyan: "8, 145, 178",
    lime: "101, 163, 13", brown: "146, 64, 14", black: "100, 116, 139", white: "226, 232, 240",
  }),
});
